[tool.poetry]
name = "py-notes-poetry"
version = "0.1.0"
description = ""
authors = ["Daniel <daniel.palacz@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]



[tool.poetry.dependencies]
python = ">=3.10"
aiofiles = "==24.1.0"
aiohappyeyeballs = "==2.4.3"
aiohttp = "==3.11.7"
aiosignal = "==1.3.1"
async-timeout = "==5.0.1"
attrs = "==24.2.0"
blinker = "==1.9.0"
click = "==8.1.7"
flask = "==3.1.0"
frozenlist = "==1.5.0"
idna = "==3.10"
itsdangerous = "==2.2.0"
jinja2 = "==3.1.4"
markupsafe = "==3.0.2"
multidict = "==6.1.0"
propcache = "==0.2.0"
typing-extensions = "==4.12.2"
werkzeug = "==3.1.3"
yarl = "==1.18.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

